
#!/bin/bash

# Use this to check the values are what you think they are

echo "ENTRAID_FEDCRED"
echo $ENTRAID_FEDCRED

echo "PRIVATE_KEY"
echo $PRIVATE_KEY
echo "PUBLIC_KEY"
echo $PUBLIC_KEY
echo "CSR_CONFIG"
echo $CSR_CONFIG
echo "CSR_FILE"
echo $CSR_FILE
echo "SELF_SIGNED"
echo $SELF_SIGNED

echo "RESOURCE_GROUP"
echo $RESOURCE_GROUP
echo "LOCATION"
echo $LOCATION
echo "TENANT_ID"
echo $TENANT_ID

echo "AZURE_STORAGE_ACCOUNT"
echo $AZURE_STORAGE_ACCOUNT
echo "AZURE_STORAGE_CONTAINER"
echo $AZURE_STORAGE_CONTAINER
echo "USER_ASSIGNED_MANAGED_IDENTITY_NAME"
echo $USER_ASSIGNED_MANAGED_IDENTITY_NAME


echo "OIDC_CONFIG"
echo $OIDC_CONFIG
echo "JWKS_DOC"
echo $JWKS_DOC
echo "SERVICE_ACCOUNT_ISSUER"
echo $SERVICE_ACCOUNT_ISSUER
echo "SERVICE_ACCOUNT_NAME"
echo $SERVICE_ACCOUNT_NAME
echo "TOKEN_AUDIENCE"
echo $TOKEN_AUDIENCE

echo "KEYVAULT_NAME"
echo $KEYVAULT_NAME
echo "KEYVAULT_SECRET_NAME"
echo $KEYVAULT_SECRET_NAME
